steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west3-docker.pkg.dev/$PROJECT_ID/nestjs-gcp/nestjs-gcp-app:latest', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'europe-west3-docker.pkg.dev/$PROJECT_ID/nestjs-gcp/nestjs-gcp-app:latest']